### ISSUE TITLE
File name error

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#25]
![image](https://user-images.githubusercontent.com/40325840/195995325-40132aac-6572-4431-9ba8-8b16c6373df4.png)

![image](https://user-images.githubusercontent.com/40325840/195995353-0a391616-d384-46a4-8500-715fd2613992.png)

**Boxes Version**
2.0.90

**Comment by sellscompany** [comment]
Hi! The problem on the local server "OpenServer" the file names are spelled correctly. I didn't find a solution. Thank you for your help!

**Comment by patrick-durrer** [comment]
Thanks for your report! 

Unfortunately, I cannot reproduce the error at this moment. Can you provide us with more information? Can you deposit the content of your partial and YAML file in this thread?

Thanks!

**Comment by sellscompany** [comment]
This file .yaml works from the plugin, but does not work in the theme.

https://disk.yandex.ru/d/5MpJnyKgxnY5nw

```
handle: test
name: test
form:
    fields:
        title:
            label: test
            type: text
```

![image](https://user-images.githubusercontent.com/40325840/196109713-acf6d545-5769-47a4-bb3f-1dda13598481.png)

**Comment by sellscompany** [comment]
On a new installation of OctoberCMS with the Demo theme, the situation is reproduced.

![image](https://user-images.githubusercontent.com/40325840/196113194-26248609-a980-4c04-b2bb-ab0646f5129e.png)

**Comment by patrick-durrer** [comment]
What is the content of your `test.htm`?

**Comment by sellscompany** [comment]
`<div class="test">test</div>`

**Comment by patrick-durrer** [comment]
Okay - It doesn't seem to come from the partial. To be honest, I can't reproduce the error in any configuration. Could you also paste in the full stack trace from the error (can be found in the system.log)?

**Comment by sellscompany** [comment]
Yes, here is the information
```
[2022-10-17 07:18:00] local.ERROR: ValidationException: Ошибка в имени файла: C:\OpenServer\domains\testboxes\themes\demo\partials\test.htm. Имена файлов могут содержать только латинские буквы, цифры, знаки подчеркивания и точки. Пример правильных имен файлов: page.htm, page, subdirectory/page in C:\OpenServer\domains\testboxes\modules\cms\classes\CmsObject.php:330
Stack trace:
#0 C:\OpenServer\domains\testboxes\modules\cms\classes\CmsObject.php(116): Cms\Classes\CmsObject::throwHalcyonException()
#1 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(977): Cms\Classes\CmsObject::loadCached()
#2 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(1017): Cms\Classes\Controller->loadPartialObject()
#3 C:\OpenServer\domains\testboxes\plugins\offline\boxes\classes\partial\Partial.php(80): Cms\Classes\Controller->renderPartial()
#4 C:\OpenServer\domains\testboxes\plugins\offline\boxes\models\Box.php(172): OFFLINE\Boxes\Classes\Partial\Partial->render()
#5 C:\OpenServer\domains\testboxes\plugins\offline\boxes\models\Page.php(318): OFFLINE\Boxes\Models\Box->render()
#6 [internal function]: OFFLINE\Boxes\Models\Page->OFFLINE\Boxes\Models\{closure}()
#7 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(560): array_map()
#8 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(719): Illuminate\Support\Arr::map()
#9 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Collection.php(359): Illuminate\Support\Collection->map()
#10 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(587): Illuminate\Database\Eloquent\Collection->map()
#11 C:\OpenServer\domains\testboxes\plugins\offline\boxes\models\Page.php(319): Illuminate\Support\Collection->implode()
#12 C:\OpenServer\domains\testboxes\vendor\twig\twig\src\Extension\CoreExtension.php(1607): OFFLINE\Boxes\Models\Page->render()
#13 C:\OpenServer\domains\testboxes\modules\cms\twig\GetAttrNode.php(147): twig_get_attribute()
#14 C:\OpenServer\domains\testboxes\storage\cms\twig\f7\f73e853838ab4727887a19340490553a895279dc1e69d2d30e2ff97db41550ae.php(37): Cms\Twig\GetAttrNode::customGetAttribute()
#15 C:\OpenServer\domains\testboxes\vendor\twig\twig\src\Template.php(394): __TwigTemplate_c33a73fd1ee4105a3e6c0619685bafeff564ae7165fb75024e589313d0f9f015->doDisplay()
#16 C:\OpenServer\domains\testboxes\vendor\twig\twig\src\Template.php(367): Twig\Template->displayWithErrorHandling()
#17 C:\OpenServer\domains\testboxes\vendor\twig\twig\src\Template.php(379): Twig\Template->display()
#18 C:\OpenServer\domains\testboxes\vendor\twig\twig\src\TemplateWrapper.php(40): Twig\Template->render()
#19 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(1092): Twig\TemplateWrapper->render()
#20 [internal function]: Cms\Classes\Controller->renderPartial()
#21 C:\OpenServer\domains\testboxes\modules\cms\classes\ComponentBase.php(153): call_user_func_array()
#22 C:\OpenServer\domains\testboxes\plugins\offline\boxes\components\BoxesPageEditor.php(45): Cms\Classes\ComponentBase->renderPartial()
#23 C:\OpenServer\domains\testboxes\modules\system\traits\DependencyMaker.php(29): OFFLINE\Boxes\Components\BoxesPageEditor->onRefreshBoxesPreview()
#24 C:\OpenServer\domains\testboxes\modules\cms\classes\ComponentBase.php(197): Cms\Classes\ComponentBase->makeCallMethod()
#25 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(881): Cms\Classes\ComponentBase->runAjaxHandler()
#26 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(714): Cms\Classes\Controller->runAjaxHandler()
#27 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(365): Cms\Classes\Controller->execAjaxHandlers()
#28 C:\OpenServer\domains\testboxes\modules\cms\classes\Controller.php(218): Cms\Classes\Controller->runPage()
#29 C:\OpenServer\domains\testboxes\modules\cms\classes\CmsController.php(64): Cms\Classes\Controller->run()
#30 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Cms\Classes\CmsController->run()
#31 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#32 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#33 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#34 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Router.php(725): Illuminate\Routing\Route->run()
#35 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#36 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#38 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#40 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#42 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#43 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#45 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then()
#49 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#50 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Routing\Router.php(667): Illuminate\Routing\Router->runRoute()
#51 C:\OpenServer\domains\testboxes\vendor\october\rain\src\Router\CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#52 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#53 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#54 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 C:\OpenServer\domains\testboxes\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#56 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#57 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#59 C:\OpenServer\domains\testboxes\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#60 C:\OpenServer\domains\testboxes\index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#61 {main}
```

**Comment by patrick-durrer** [comment]
Looks like you try to load the partial with a absolute path: `C:\OpenServer\domains\testboxes\themes\demo\partials\test.htm` - the integrated name validation of october - that is also used by Boxes Plugin - validates the Filename by the following regex: `^[a-z0-9\_\s\-\.\/]+$` (modules\cms\helpers\Cms.php [22]). So the `:` causes the `ValidationException`.

Do you probably know, why it renders absolute paths on your setup? Is this related to your OpenServer setup (Sorry, we have no experience with this environment)?

Thanks for your help!

**Comment by patrick-durrer** [comment]
Contrary to our first assumption, the problem is probably not the colon, but the backslashes - these do not pass the validation of the October CMS RegEx (`^[a-z0-9\_\s\-\.\/]+$`).

In order to be able to place the Boxes files anywhere in the application, we cannot work with the normal file designation for the renderPartial function.

`->renderPartial('boxes/text')`

We have to see if and how we can tackle this problem. We'll keep you updated with this thread.

**Comment by tobias-kuendig** [comment]
@sellscompany do you still experience this issue with current verions?

**Comment by sellscompany** [comment]
Yes, the problem persists. But it's not about the plugin, so the issue can be closed
